networks:
  kafka-network:
    name: kafka-network
    external: true
    driver: bridge


services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - kafka-network
    restart: always
